
trigger:
  branches:
    include:
      - features/*
      - main

pool:
  jay

variables:
  working-path: '$(System.DefaultWorkingDirectory)/Dev'

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(working-path)'
    backendServiceArm: 'jay'
    backendAzureRmResourceGroupName: 'jay_rg'
    backendAzureRmStorageAccountName: 'jaystg'
    backendAzureRmContainerName: 'jaycnt'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(working-path)'
    environmentServiceNameAzureRM: 'jay'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(working-path)'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: 'jay'