# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  jay

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Dev'
    backendServiceArm: 'jay'
    backendAzureRmResourceGroupName: 'Jaydeeprg'
    backendAzureRmStorageAccountName: 'jaydeepstg'
    backendAzureRmContainerName: 'jaydeepcnt'
    backendAzureRmKey: 'terraform.tfstate'